### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by kloczek** [jmcantrell/python-dateutils#12]
In PKG-INFO it is:
```
License: UNKNOWN
```
However LICENSE content looks very simillar to MIT licence.
Similar but not the same :)
https://opensource.org/licenses/MIT/

**Comment by jmcantrell** [comment]
I'm not sure what you're referring to. The license is defined in setup.py as BSD, and github recognizes it as BSD zero clause. Closing this for now.

**Comment by kloczek** [comment]
Indeed it is in setup.py:
```
        'License :: OSI Approved :: BSD License',
```
Issue is that there are at least 3 BSD licenses.
BSD-2-Clause (https://opensource.org/licenses/BSD-2-Clause/)
BSD-3-Clause (https://opensource.org/licenses/BSD-3-Clause/)
BSD-4-Clause (https://spdx.org/licenses/BSD-4-Clause.html)
And that License tag is noit propagated into generated PKG-INFO file.

**Comment by kloczek** [comment]
And what is lin LICENSE file looks more like MIT (https://opensource.org/licenses/MIT/)

**Comment by jmcantrell** [comment]
It looks like there's not a recommended solution yet for the trove classifier imprecision:

https://github.com/pypa/trove-classifiers/issues/17
https://discuss.python.org/t/pep-639-improving-license-clarity-with-better-package-metadata/2154

Regarding the license file, it's exactly this:
https://opensource.org/licenses/0BSD
