### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by mpadilla2** [jmcantrell/python-dateutils#2]
Hi Jeremy, thank you for writing this package. I wanted to get clarification on what the current version of the package is. Here on github it shows 0.6.5 but on pypi.python.org it shows 0.6.6. However, the version on pypi doesn't contain the reference to python3.

**Comment by svetlyak40wt** [comment]
I'm wondering if Jeremy will be so kind and will push his changes to the repository. Otherwise, my petproject AllMyChanges [does not see](https://allmychanges.com/p/python/dateutils/) the latest release.

**Comment by jmcantrell** [comment]
I apologize for my inattentiveness here.

There have been some recent changes and I've made sure it's in sync with pypi. I'm going to close this for now. Let me know if there's still something that needs to happen.
