### ISSUE TITLE
Copy of BSD License

### ISSUE THREAD

**Issue by mpadilla2** [jmcantrell/python-dateutils#3]
Do you have a copy of the BSD license that shows the copyright year, etc? I'd like to create an archlinux package which would require the BSD license copy.

**Comment by jayvdb** [comment]
Ping, I'd like to package this also, but there is no license file.

**Comment by smoe** [comment]
Same here. There are different versions of the BSD license and the license also requires to be shippped with the sources.

**Comment by jmcantrell** [comment]
I changed the license to public domain. You should be able to do whatever you need now.

**Comment by jayvdb** [comment]
Unfortunately, that doesnt help with distro packaging.

Their default policy requires a license file in the repo which uses an OSS approved license text.  By not using one, legal folks need to get involved.  And they are going to have difficulty with you claiming public domain without sign-off by the other [contributors](https://github.com/jmcantrell/python-dateutils/graphs/contributors).

fwiw, I agree to the relicensing for my trivial change, and I expect all of those contributions by others are too trivial and non-creative to be worth a copyright, but lawyers tend to be overly cautious.

It would be much easier if this was re-licensed back to BSD-2-Clause or BSD-3-Clause.

**Comment by jmcantrell** [comment]
I apologize if this has caused any problems. I only made that change in an effort to make it easier use.

I've changed the license back to BSD (zero-clause), and included a LICENSE file.

**Comment by sunpoet** [comment]
> I've changed the license back to BSD (zero-clause), and included a LICENSE file.

Could you please also put the LICENSE file into the sdist?
Thanks!

**Comment by jmcantrell** [comment]
Done.

**Comment by sunpoet** [comment]
Thanks! I've also [updated the FreeBSD port](https://svnweb.freebsd.org/changeset/ports/547094).

**Comment by jayvdb** [comment]
Thanks. Pushed into openSUSE https://build.opensuse.org/package/show/devel:languages:python/python-dateutils
